StOnline/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve

import users
from settings import MEDIA_ROOT,STATIC_ROOT


from django.views.generic import TemplateView
from users.views import LoginView,RegisterView,ActiveUserView,LogoutView,BeTeacher,Index
from organization.views import OrgView

import xadmin

urlpatterns = [
    url(r'^$', Index.as_view(), name="index"),
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),

    url('^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url('^register/$',RegisterView.as_view(),name='register'),


    url(r'^captcha/',include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),


    url(r'^static/(?P<path>.*)', serve, {"document_root": STATIC_ROOT}),
    url(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),




    url(r'^org/', include('organization.urls', namespace='org')),
    url(r'courses/', include('courses.urls', namespace='course')),
    url(r'^users/', include('users.urls', namespace='users')),







]

apps/courses/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import CourseListView,CourseDetailView, CourseInfoView, CommentsView,AddCommentsView,VideoPlayView



urlpatterns = [
    # 课程列表页
    url(r'^list/$', CourseListView.as_view(), name='course_list'),

    # # 课程详情页
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    #
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    #
    url(r'^comments/(?P<course_id>\d+)/$', CommentsView.as_view(), name='course_comments'),
    #
    # # 添加课程评论
    url(r'^add_comment/$', AddCommentsView.as_view(), name='add_comment'),
    #
    #
    url(r'^video/(?P<video_id>\d+)$', VideoPlayView.as_view(), name='video_play'),

]

apps/organization/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from .views import OrgView,OrganizationHomeView,OrganizationCourseView,OrganizationDescView,OrganizationTeacherView, \
    AddFavView,TeacherListView,TeacherDetailView

urlpatterns = [

    url('^list/$', OrgView.as_view(), name='org_list'),

    # url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    url(r'^home/(?P<org_id>\d+)/$', OrganizationHomeView.as_view(), name="org_home"),
    url(r'^course/(?P<org_id>\d+)/$', OrganizationCourseView.as_view(), name="org_course"),
    url(r'^desc/(?P<org_id>\d+)/$', OrganizationDescView.as_view(), name="org_desc"),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrganizationTeacherView.as_view(), name="org_teacher"),
    #
    #
    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),
    #
    # # 讲师列表页
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),

    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail"),
]

apps/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from users.forms import UploadCourseImgForm
from .views import UserInfoView, UploadImageView, UpdatePwdView, \
    SendMailCodeView, UpdateEmailView, MyCourseView, \
    MyFavOrgView, MyFavTeacherView, MyFavCourseView,\
    MyMessageView,BeTeacher,Publish,SendMsg, UploadCourseImgView

urlpatterns = [

    url('^send_msg/$', SendMsg.as_view(), name='send_msg'),

    url('^to_be_teacher/$', BeTeacher.as_view(), name='be_teacher'),

    url(r'^publish/$', Publish.as_view(), name='user_publish'),

    # 用户信息
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),

    # 用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),

    url(r'^course_image/upload/(?P<course_id>\d+)/$', UploadCourseImgView.as_view(), name='course_image_upload'),

    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),

    # 用户中心修改邮箱
    url(r'^sendemail_code/$', SendMailCodeView.as_view(), name='sendemail_code'),

    # 修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    # 我的课程
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),

    # 我收藏的课程机构
    url(r'^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),

    # 我收藏的授课讲师
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),

    # 我收藏的课程
    url(r'^myfav/course/$', MyFavCourseView.as_view(), name='myfav_course'),

    # 我的消息
    url(r'^mymessage/$', MyMessageView.as_view(), name='mymessage'),

]

apps/courses/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from datetime import datetime

from django.db import models

from DjangoUeditor.models import UEditorField

from organization.models import CourseOrganization, Teacher

# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrganization, verbose_name=u"课程机构名称", null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u"课程名称")
    desc = models.CharField(max_length=300, verbose_name=u"课程描述")
    click_num = models.IntegerField(default=0, verbose_name=u"点击数")
    detail = models.CharField(max_length=300,verbose_name = u"课程详情")
    teacher = models.ForeignKey(Teacher, verbose_name=u"讲师", null=True, blank=True)
    degree = models.CharField(choices=(("cj", "初级"), ("zj", "中级"), ("gj", "高级")), max_length=2, verbose_name=u"难度")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图")
    tag = models.CharField(choices=(("sf", "算法"), ("pt", "python语法"), ("ap", "应用"),("zn","人工智能"),("ot","其他")),default="ot", max_length=20, verbose_name=u"课程标签")
    # tag = models.CharField(default="", max_length=10, verbose_name=u"课程标签")
    youneed_know = models.CharField(default="", max_length=300, verbose_name=u"课程须知")
    # teacher_tell = models.CharField(default="", max_length=300, verbose_name=u"老师告诉你")
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取课程章节数
        all_lessons = self.lesson_set.all().count()
        return all_lessons
    get_zj_nums.short_description = "章节数"

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='https://www.baidu.com'>跳转</a>")
    go_to.short_description = "跳转"

    def get_learn_users(self):
        # 取出5个用户
        return self.usercourse_set.all()[:5]



    def get_course_lessons(self):
        # 获取所有课程章节
        return self.lesson_set.all()

    def __unicode__(self):
        return self.name


class BannerCourse(Course):
    class Meta:
        verbose_name = "轮播课程"
        verbose_name_plural = verbose_name
        proxy = True


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_lesson_video(self):
        # 获取章节视频
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节")
    name = models.CharField(max_length=100, verbose_name=u"视频名称")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    url = models.CharField(max_length=500, default="", verbose_name=u"访问地址")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"资源名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

templates/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
评论
{% endblock %}

{% block custom_bread %}
<!--crumbs start-->
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="/">首页</a>></li>
                    <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />

{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="/login/";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });

</script>
{% endblock %}

{% block content %}

    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'course:course_comments' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">

                            {% for course_comment in course_comments %}

                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ course_comment.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ course_comment.user.username }}</span>
                                    </div>
                                    <p class="cnt">{{ course_comment.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ course_comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>

                            {% endfor %}

                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">

                            {% for course_resource in course_resources %}
                                <li>
                                    <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_resource.name }}</span>
                                    <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                       <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">

                                        {% for relate_course in relate_courses %}

                                            <li class="curr">
                                            <a href="{% url 'course:course_detail' relate_course.id %}" target="_blank">
                                                <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name }}">
                                                <span class="name autowrap">{{ relate_course.name }}</span>
                                            </a>
                                        </li>

                                        {% endfor %}

                                    </ul>
                                </div>

                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>

{% endblock %}

templates/org_base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} 机构首页 {% endblock %}

{% block custome_css %} {% endblock %}
{% block custome_js %} {% endblock %}

{% block custom_bread %}
<!--crumbs start-->
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>课程机构</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block content %}

<section class="headerwrap headerwrap2">
    <header>



    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                      {{course_org.name }}
{#                    <img src="{% static 'images/authentication.png' %}"/>#}
{#                    <img src="{% static 'images/gold.png' %}"/>#}
                </h1>
{#                <p class="fl">#}
{#                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>#}
{#                    <span class="precision company-credit" data-star-scope="5.0"></span>#}
{#                    <span class="key">5.0</span>#}
{#                </p>#}
            </div>
            <div class="btn fr collectionbtn  notlogin">
                 {% if has_fav %}
                    已收藏
                 {% else %}
                     收藏
                 {% endif %}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block page_path %} 机构首页 {% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %} active2 {% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %} active2 {% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %} active2 {% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %} active2 {% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>
    
    {% block right_form %}

    {% endblock %}

</section>

{% endblock %}




{% block custom_js %}
<script>
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

{#$(function(){#}
{#    var $precision = $('.precision'),#}
{#        score = $precision.attr('data-star-scope'),#}
{#        option =  {#}
{#                    half		: true,#}
{#                    path		: '{% static 'images/' %}',#}
{#                    precision	: true,#}
{#                    size		: 24,#}
{#                    starOff		: 'g_star.png',#}
{#                    starOn		: 'r_star.png',#}
{#                    starHalf	: 'h_star.png',#}
{#                    hints       : ['极差', '差', '一般', '好评', '非常满意'],#}
{#                    noRatedMsg  : '暂时还未获得评价！',#}
{#                    readOnly    : true,#}
{#                    score       : score#}
{#                };#}
{#    $precision.raty(option);#}
{##}
{#    $('.jsFavBtn').on('click', function(){#}
{#        var type = $(this).attr('data-fav-type');#}
{#        if(type == '1'){#}
{#            favPraise($(this), 'fav' ,1 , '收藏');#}
{##}
{#        }else if(type == '3'){#}
{#            favPraise($(this), 'fav' ,3 );#}
{##}
{#        }else if(type == '11'){#}
{#            favPraise($(this), 'pra', 1);#}
{##}
{#        }else if(type == '4'){#}
{#            favPraise($(this), 'fav' ,4 );#}
{##}
{#        }#}
{#    });#}

</script>

{##}
{#<script type="text/javascript">#}
{#$(function() {#}
{#    $('.recordbtn1').click(function(){#}
{#        $('.recordbox1').show();#}
{#    });#}
{#    $('.recordbtn2').click(function(){#}
{#        $('.recordbox2').show();#}
{#    });#}
{##}
{#    $('.imgslide').unslider({#}
{#        speed: 500,               //  The speed to animate each slide (in milliseconds)#}
{#        delay: 3000,              //  The delay between slide animations (in milliseconds)#}
{#        complete: function() {},  //  A function that gets called after every slide animation#}
{#        keys: true,               //  Enable keyboard (left, right) arrow shortcuts#}
{#        dots: true,               //  Display dot navigation#}
{#        fluid: false              //  Support responsive design. May break non-responsive designs#}
{#    });#}
{#    var unslider = $('.imgslide').unslider();#}
{#    $('.unslider-arrow').click(function() {#}
{#        var fn = this.className.split(' ')[1];#}
{#        unslider.data('unslider')[fn]();#}
{#    });#}
{#});#}
{##}
{#</script>#}
{% endblock %}

templates/usercenter-beteacher.html
{% extends 'usercenter-base.html' %}
{% block right_content %}
    <div class="right">
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>教师信息</h1>
			</div>
			<div class="inforcon">
				<form class="perinform" action="{% url "users:be_teacher" %}" method="post" id="jsEditUserForm" autocomplete="off">
					<ul class="right" style="margin-left: -500px">
                        <li>工 作 年 限：
                           <input type="text" name="work_years" id="work_years" value="" maxlength="100">
                            <i class="error-tips"></i>
                        </li>
                        <li>就 职 公 司：
                           <input type="text" name="work_company" id="work_company" value="" maxlength="100">
                            <i class="error-tips"></i>
                        </li>
                        <li>公 司 职 位：
                           <input type="text" name="work_position" id="work_position" value="" maxlength="100">
                            <i class="error-tips"></i>
                        </li>
                        <li>教 学 特 点：
                           <input type="text" name="points" id="points" value="" maxlength="100">
                            <i class="error-tips"></i>
                        </li>
                        <li class="button heibtn">
							<input type="submit" id="jsEditUserBtn" value="保存">
						</li>


					</ul>
                    {% csrf_token %}
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}

{% block title %}
我的收藏
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}

                            <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}

{% block title %}
我的收藏
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}

    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">

                    {% for org in org_list %}

                        <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>

                    {% endfor %}

                </div>
            </div>
        </div>

{% endblock %}